import { writeFileSync } from "node:fs";
import { join } from "node:path";

const favicon = (domain) =>
  `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;

const UNSPLASH = {
  writing:
    "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&w=1600&q=80",
  image:
    "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1600&q=80",
  video:
    "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=1600&q=80",
  productivity:
    "https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=1600&q=80",
  design:
    "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1600&q=80",
  coding:
    "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1600&q=80",
  chat:
    "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1600&q=80",
  audio:
    "https://images.unsplash.com/photo-1478737271069-78c9d5ff805b?auto=format&fit=crop&w=1600&q=80",
  startup:
    "https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=1600&q=80",
  indie:
    "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1600&q=80",
  free:
    "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=80",
  marketing:
    "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1600&q=80",
  youtube:
    "https://images.unsplash.com/photo-1611162616305-c69b3a7a0d02?auto=format&fit=crop&w=1600&q=80",
  meeting:
    "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=1600&q=80",
  music:
    "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1600&q=80",
  automation:
    "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1600&q=80",
  creator:
    "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1600&q=80",
  support:
    "https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1600&q=80",
  alternatives:
    "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1600&q=80",
  presentation:
    "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1600&q=80",
};

function tool(
  id,
  name,
  domain,
  category,
  desc,
  features,
  pros,
  cons,
  pricing,
  alternatives,
  faq = [],
) {
  return {
    id,
    name,
    logo: favicon(domain),
    category,
    description: desc,
    features,
    pros,
    cons,
    pricing,
    faq,
    alternatives,
  };
}

const tools = [
  // AI Chatbots (1-8)
  tool(
    1,
    "ChatGPT",
    "chatgpt.com",
    "AI Chatbots",
    "ChatGPT is the best AI chatbot for everyday conversation, research, coding help, and content drafting. This free AI assistant from OpenAI supports GPT-4o, file uploads, custom GPTs, and plugins—ideal for marketers, students, and indie hackers who need a reliable AI copilot in 2026.",
    [
      "GPT-4o multimodal chat",
      "Custom GPTs & Actions",
      "Web browsing & data analysis",
      "Voice conversation mode",
      "Team & Enterprise workspaces",
    ],
    [
      "Industry-leading reasoning",
      "Huge plugin & GPT ecosystem",
      "Strong free tier for testing",
    ],
    ["Plus required for best models", "Can hallucinate on niche facts"],
    "Free / ChatGPT Plus $20/mo",
    ["Claude", "Google Gemini", "Perplexity"],
    [
      {
        question: "Is ChatGPT still the best free AI chatbot in 2026?",
        answer:
          "Yes—ChatGPT remains the most popular free AI chatbot with generous limits on the free plan and advanced features on Plus.",
      },
      {
        question: "Can ChatGPT write SEO blog posts?",
        answer:
          "Absolutely. ChatGPT is widely used as a free AI writer for outlines, drafts, meta descriptions, and keyword-rich content.",
      },
    ],
  ),
  tool(
    2,
    "Claude",
    "claude.ai",
    "AI Chatbots",
    "Claude by Anthropic is a top-rated AI chatbot for long documents, safe enterprise use, and nuanced writing. Best AI tool for analyzing PDFs, contracts, and codebases with a massive context window—perfect for professionals who need accurate, thoughtful AI assistance.",
    [
      "200K+ token context window",
      "Artifacts & Projects",
      "Strong coding & reasoning",
      "Enterprise SSO & compliance",
      "Claude 3.5 Sonnet & Opus models",
    ],
    ["Excellent long-form analysis", "Natural, human-like tone", "Strong safety policies"],
    ["No native image generation", "Free tier has usage caps"],
    "Free / Pro $20/mo / Team & Enterprise",
    ["ChatGPT", "Google Gemini", "Perplexity"],
  ),
  tool(
    3,
    "Google Gemini",
    "gemini.google.com",
    "AI Chatbots",
    "Google Gemini is the best free AI chatbot integrated with Google Search, Docs, and Android. Use this AI assistant for real-time answers, multimodal prompts with images, and workspace productivity—an essential AI tool for Google ecosystem users in 2026.",
    [
      "Live web access via Google",
      "Image & video understanding",
      "Gemini Advanced (Ultra)",
      "Workspace side panel",
      "Mobile & Chrome integration",
    ],
    ["Up-to-date information", "Deep Google integration", "Competitive free access"],
    ["UI less flexible than ChatGPT", "Feature rollout varies by region"],
    "Free / Google One AI Premium",
    ["ChatGPT", "Claude", "Microsoft Copilot"],
  ),
  tool(
    4,
    "Microsoft Copilot",
    "copilot.microsoft.com",
    "AI Chatbots",
    "Microsoft Copilot is the best AI chatbot for Windows, Edge, and Microsoft 365 users. Free AI assistant powered by OpenAI models with Bing search, Designer image creation, and Office Copilot—ideal for enterprise teams standardizing on Microsoft.",
    [
      "Bing & web-grounded answers",
      "Copilot in Word, Excel, Teams",
      "DALL·E image generation",
      "Enterprise Microsoft 365 Copilot",
      "Free tier in Edge & Windows",
    ],
    ["Seamless Microsoft 365 tie-in", "Free access for many users", "Strong enterprise story"],
    ["Best features need M365 license", "Consumer UX can feel fragmented"],
    "Free / Microsoft 365 Copilot add-on",
    ["ChatGPT", "Google Gemini", "Claude"],
  ),
  tool(
    5,
    "Perplexity",
    "perplexity.ai",
    "AI Chatbots",
    "Perplexity is the best AI search chatbot for cited, up-to-date answers. This free AI research assistant combines LLMs with live web retrieval—perfect for journalists, students, and SEO professionals who need trustworthy sources in every response.",
    [
      "Inline citations & sources",
      "Pro Search deep research",
      "Focus modes (Academic, Writing)",
      "File & PDF upload",
      "Perplexity Pages publishing",
    ],
    ["Transparent sourcing", "Excellent for research", "Fast factual Q&A"],
    ["Less creative than ChatGPT", "Pro needed for heavy use"],
    "Free / Perplexity Pro $20/mo",
    ["ChatGPT", "Google Gemini", "Claude"],
  ),
  tool(
    6,
    "Poe",
    "poe.com",
    "AI Chatbots",
    "Poe by Quora is the best AI chatbot aggregator for trying GPT-4, Claude, Gemini, and open models in one app. A must-have free AI tool for power users who want side-by-side model comparison and custom bots without juggling multiple subscriptions.",
    [
      "Multi-model access in one UI",
      "Create & share custom bots",
      "Mobile & desktop apps",
      "Bot monetization for creators",
      "Fast model switching",
    ],
    ["One hub for many LLMs", "Affordable bundled access", "Great for experimentation"],
    ["Credit-based pricing on some models", "Dependent on third-party APIs"],
    "Free / Poe subscription plans",
    ["ChatGPT", "Claude", "Character.AI"],
  ),
  tool(
    7,
    "Character.AI",
    "character.ai",
    "AI Chatbots",
    "Character.AI is the best free AI chatbot platform for roleplay, entertainment, and persona-driven conversations. Create custom AI characters for storytelling, language practice, and community engagement—hugely popular with Gen Z creators in 2026.",
    [
      "Custom character creation",
      "Group chats with multiple AIs",
      "Voice-enabled characters",
      "Community character library",
      "Mobile-first experience",
    ],
    ["Highly engaging personas", "Strong free experience", "Viral social features"],
    ["Not ideal for business workflows", "Content moderation concerns"],
    "Free / c.ai+ subscription",
    ["Poe", "ChatGPT", "Meta AI"],
  ),
  tool(
    8,
    "Meta AI",
    "meta.ai",
    "AI Chatbots",
    "Meta AI is the best free AI chatbot built into Instagram, WhatsApp, and Facebook. Use this AI assistant for image generation with Emu, real-time answers, and social sharing—ideal for creators and small businesses already on Meta platforms.",
    [
      "Llama-powered chat",
      "In-app integration (IG, WA)",
      "AI image & sticker creation",
      "Ray-Ban Meta glasses support",
      "Free for Meta account holders",
    ],
    ["Zero friction for Meta users", "Free image gen in chat", "Massive distribution"],
    ["Limited standalone web features", "Privacy considerations on Meta apps"],
    "Free",
    ["ChatGPT", "Google Gemini", "Character.AI"],
  ),

  // AI Writing (9-16)
  tool(
    9,
    "Jasper AI",
    "jasper.ai",
    "AI Writing",
    "Jasper is the best AI writing tool for marketing teams and brand-safe content at scale. This premium AI copywriter offers campaigns, SEO mode, and team workflows—top choice for agencies needing on-brand blogs, ads, and email sequences in 2026.",
    [
      "Brand Voice & Knowledge",
      "SEO-optimized blog workflows",
      "50+ marketing templates",
      "Campaign briefs & approvals",
      "Integrations (Surfer, CMS)",
    ],
    ["Enterprise marketing focus", "Consistent brand tone", "Collaboration features"],
    ["Premium pricing", "Learning curve for workflows"],
    "Creator $49/mo / Pro / Business",
    ["Copy.ai", "Writesonic", "Anyword"],
  ),
  tool(
    10,
    "Copy.ai",
    "copy.ai",
    "AI Writing",
    "Copy.ai is the best free AI writer for sales copy, social posts, and GTM workflows. This AI copywriting platform includes Chat, Workflows, and Infobase—perfect for startups and indie hackers who need fast, conversion-focused content without a big budget.",
    [
      "GTM & sales workflows",
      "90+ copy templates",
      "Brand voice & Infobase",
      "Multi-language output",
      "API & Zapier automation",
    ],
    ["Generous free tier", "Strong for GTM teams", "Workflow automation"],
    ["Long-form needs editing", "Advanced SEO on higher tiers"],
    "Free / Pro from $49/mo",
    ["Jasper", "Writesonic", "Rytr"],
  ),
  tool(
    11,
    "Writesonic",
    "writesonic.com",
    "AI Writing",
    "Writesonic is a top AI writing tool combining Chatsonic, Article Writer, and SEO optimization. Best AI platform for bloggers and ecommerce brands who want GPT-4 quality articles, product descriptions, and landing pages with built-in keyword research.",
    [
      "AI Article Writer 6.0",
      "Chatsonic with web access",
      "SEO checker & internal links",
      "Photosonic image add-on",
      "Bulk generation & API",
    ],
    ["All-in-one content stack", "Competitive pricing", "Good SEO tooling"],
    ["UI can feel busy", "Quality varies by template"],
    "Free trial / plans from ~$16/mo",
    ["Jasper", "Copy.ai", "Rytr"],
  ),
  tool(
    12,
    "Grammarly",
    "grammarly.com",
    "AI Writing",
    "Grammarly is the best AI writing assistant for grammar, tone, and clarity across email, docs, and browsers. Free AI proofreader trusted by millions—essential for professionals who want real-time suggestions, plagiarism checks, and generative AI rewrites in 2026.",
    [
      "Grammar & tone suggestions",
      "Generative AI rewrite",
      "Plagiarism detection",
      "Browser & Office extensions",
      "Team style guides",
    ],
    ["Ubiquitous integrations", "Reliable proofreading", "Strong enterprise adoption"],
    ["Not a full long-form writer", "Premium for advanced AI"],
    "Free / Premium / Business",
    ["Wordtune", "Jasper", "ChatGPT"],
  ),
  tool(
    13,
    "Rytr",
    "rytr.me",
    "AI Writing",
    "Rytr is the best budget AI writer for blogs, emails, and ads in 40+ languages. Affordable free AI writing tool with tone presets and SEO templates—ideal for solopreneurs and content marketers testing AI copy without enterprise pricing.",
    [
      "40+ languages & 20+ tones",
      "Blog outline & paragraph tools",
      "SEO analyzer (paid)",
      "Chrome extension",
      "MyVoice custom tone",
    ],
    ["Very affordable", "Simple interface", "Good multilingual support"],
    ["Output needs human polish", "Fewer integrations than Jasper"],
    "Free / Saver $9/mo / Unlimited $29/mo",
    ["Writesonic", "Copy.ai", "Anyword"],
  ),
  tool(
    14,
    "Wordtune",
    "wordtune.com",
    "AI Writing",
    "Wordtune is the best AI writing tool for rewriting sentences and improving readability. Free AI paraphraser and summarizer for academics and professionals who need crisp emails, papers, and LinkedIn posts with multiple rewrite tones.",
    [
      "Rewrite & spice up modes",
      "Summarize long documents",
      "Tone adjustments",
      "Browser & Word integration",
      "AI answers with sources (Read)",
    ],
    ["Excellent sentence-level edits", "Great for non-native English", "Fast inline suggestions"],
    ["Limited long-form generation", "Best features on premium"],
    "Free / Plus / Unlimited",
    ["Grammarly", "QuillBot", "ChatGPT"],
  ),
  tool(
    15,
    "Sudowrite",
    "sudowrite.com",
    "AI Writing",
    "Sudowrite is the best AI writing tool for fiction authors and novelists. Specialized AI story writer with Describe, Expand, and Brainstorm—built for creative writers who want AI-assisted prose without generic marketing templates.",
    [
      "Story Engine novel planning",
      "Describe sensory details",
      "Character & plot brainstorming",
      "Canvas visual storyboard",
      "Genre-aware models",
    ],
    ["Unmatched for fiction", "Author-centric UX", "Creative control"],
    ["Niche focus—not for marketing", "Subscription required"],
    "Hobbyist / Professional / Max plans",
    ["NovelAI", "ChatGPT", "Claude"],
  ),
  tool(
    16,
    "Anyword",
    "anyword.com",
    "AI Writing",
    "Anyword is the best AI copywriting platform with predictive performance scores for ads and landing pages. Data-driven AI writer for performance marketers who need A/B-ready headlines, email copy, and social ads optimized for conversion.",
    [
      "Predictive performance score",
      "Ad & landing page copy",
      "Brand voice & target personas",
      "Blog wizard with SEO",
      "API for marketing stacks",
    ],
    ["Performance-focused copy", "Strong for paid media", "Enterprise analytics"],
    ["Higher price point", "Less popular for casual blogging"],
    "Starter / Data-Driven / Business",
    ["Jasper", "Copy.ai", "Writesonic"],
  ),

  // AI Coding (17-24)
  tool(
    17,
    "GitHub Copilot",
    "github.com",
    "AI Coding",
    "GitHub Copilot is the best AI coding assistant for VS Code, JetBrains, and GitHub. Industry-standard AI pair programmer with Copilot Chat, Workspace, and enterprise policies—essential for developers shipping faster in 2026.",
    [
      "Inline code completions",
      "Copilot Chat in IDE",
      "Copilot Workspace (preview)",
      "CLI & GitHub.com integration",
      "Enterprise audit & policy",
    ],
    ["Deep GitHub integration", "Supports all major languages", "Huge training signal"],
    ["Subscription required", "Occasional insecure suggestions"],
    "Individual $10/mo / Business / Enterprise",
    ["Cursor", "Codeium", "Tabnine"],
    [
      {
        question: "Is GitHub Copilot the best AI coding assistant in 2026?",
        answer:
          "For GitHub-centric teams, Copilot remains the default best AI coding assistant with mature IDE support and enterprise controls.",
      },
    ],
  ),
  tool(
    18,
    "Cursor",
    "cursor.com",
    "AI Coding",
    "Cursor is the best AI IDE for agentic coding, multi-file edits, and codebase chat. Built on VS Code with Composer and Claude/GPT models—top AI coding tool for indie hackers and startups who want AI-native development workflows.",
    [
      "Composer multi-file agent",
      "Codebase indexing & @-mentions",
      "Tab autocomplete",
      "YOLO / auto-apply modes",
      "VS Code extension compatibility",
    ],
    ["Best-in-class AI IDE UX", "Fast iteration on features", "Strong model choice"],
    ["Separate editor migration", "Usage-based costs on Pro"],
    "Free / Pro $20/mo / Business",
    ["GitHub Copilot", "Windsurf", "Codeium"],
  ),
  tool(
    19,
    "Tabnine",
    "tabnine.com",
    "AI Coding",
    "Tabnine is the best AI code completion tool for privacy-focused teams. On-prem and air-gapped AI coding assistant with personalized models—ideal for enterprises that cannot send code to public cloud LLMs.",
    [
      "Local & private deployments",
      "Whole-line & full-function completion",
      "Supports 600+ languages",
      "Team model training",
      "IDE plugins everywhere",
    ],
    ["Strong privacy story", "Flexible deployment", "Low latency completions"],
    ["Less agentic than Cursor", "Premium for best models"],
    "Free / Pro / Enterprise",
    ["GitHub Copilot", "Codeium", "Amazon Q Developer"],
  ),
  tool(
    20,
    "Replit AI",
    "replit.com",
    "AI Coding",
    "Replit AI (Ghostwriter) is the best AI coding tool in the browser for learning, prototypes, and deployments. Free AI programmer with Agent, Debugger, and instant hosting—perfect for students and indie hackers building MVPs fast.",
    [
      "Replit Agent full-app builds",
      "Ghostwriter code completion",
      "In-browser IDE & deployments",
      "Collaborative multiplayer",
      "Mobile coding app",
    ],
    ["Zero local setup", "Deploy in one click", "Great for education"],
    ["Not for large legacy repos", "Compute costs add up"],
    "Free / Replit Core / Teams",
    ["GitHub Copilot", "Cursor", "Codeium"],
  ),
  tool(
    21,
    "Amazon Q Developer",
    "aws.amazon.com",
    "AI Coding",
    "Amazon Q Developer (formerly CodeWhisperer) is the best AI coding assistant for AWS workloads. Free AI code generator with security scans and Lambda-focused suggestions—must-have for cloud engineers building on AWS in 2026.",
    [
      "AWS SDK-aware completions",
      "Code reference tracking",
      "Security vulnerability scans",
      "CLI & JetBrains plugins",
      "Transformation for Java upgrades",
    ],
    ["Deep AWS integration", "Free tier for individuals", "Enterprise IAM alignment"],
    ["Weaker outside AWS context", "Less hype than Cursor"],
    "Free for individuals / Pro tiers",
    ["GitHub Copilot", "Tabnine", "Sourcegraph Cody"],
  ),
  tool(
    22,
    "Codeium",
    "codeium.com",
    "AI Coding",
    "Codeium is the best free AI coding assistant for individuals and teams. Unlimited AI autocomplete and chat in 70+ IDEs—top Copilot alternative with Windsurf editor and strong privacy options for budget-conscious developers.",
    [
      "Free individual tier",
      "Windsurf AI IDE",
      "Chat with codebase context",
      "70+ IDE extensions",
      "Self-hosted enterprise option",
    ],
    ["Generous free plan", "Fast completions", "Windsurf agent features"],
    ["Enterprise features maturing", "Brand split Codeium vs Windsurf"],
    "Free / Teams / Enterprise",
    ["GitHub Copilot", "Cursor", "Tabnine"],
  ),
  tool(
    23,
    "Sourcegraph Cody",
    "sourcegraph.com",
    "AI Coding",
    "Sourcegraph Cody is the best AI coding assistant for searching and understanding large codebases. Enterprise AI developer tool with codebase-aware chat, batch changes, and Deep Search—ideal for platform teams managing monorepos.",
    [
      "Codebase-wide context",
      "Cody chat in IDE & web",
      "Batch changes & automation",
      "Integrates with Sourcegraph search",
      "Multiple LLM backends",
    ],
    ["Excels on huge repos", "Strong enterprise search", "Open-source roots"],
    ["Setup complexity", "Pricing for large orgs"],
    "Free / Pro / Enterprise",
    ["GitHub Copilot", "Cursor", "Amazon Q Developer"],
  ),
  tool(
    24,
    "Windsurf",
    "codeium.com",
    "AI Coding",
    "Windsurf is the best AI IDE from Codeium with Cascade agentic flows and deep context. Free AI coding environment competing with Cursor—featuring Flows, live previews, and multi-step edits for full-stack developers in 2026.",
    [
      "Cascade agentic editor",
      "Real-time preview",
      "Deep codebase awareness",
      "Memories & rules",
      "Built on Codeium models",
    ],
    ["Strong agent UX", "Competitive pricing", "Rapid feature shipping"],
    ["Newer ecosystem than VS Code forks", "Naming overlap with Codeium"],
    "Free / Pro plans",
    ["Cursor", "GitHub Copilot", "Replit AI"],
  ),

  // AI Image (25-32)
  tool(
    25,
    "Midjourney",
    "midjourney.com",
    "AI Image",
    "Midjourney is the best AI image generator for artistic, cinematic visuals and Discord-native workflows. Top-rated text-to-image AI tool for designers and creators who want stunning aesthetics, style references, and v6 realism in 2026.",
    [
      "Photoreal & stylized modes",
      "Style reference (--sref)",
      "Zoom, pan, vary region",
      "Web & Discord interfaces",
      "Community prompt inspiration",
    ],
    ["Unmatched aesthetic quality", "Strong creator community", "Frequent model upgrades"],
    ["No permanent free tier", "Discord learning curve"],
    "Basic $10/mo / Standard / Pro",
    ["DALL·E 3", "Stable Diffusion", "Leonardo AI"],
  ),
  tool(
    26,
    "DALL·E 3",
    "openai.com",
    "AI Image",
    "DALL·E 3 is the best AI image generator inside ChatGPT for prompt-accurate, readable text in images. Free AI art tool (with limits) for marketers needing quick social graphics, concept art, and ad creatives without learning complex UIs.",
    [
      "Natural language prompts",
      "Text rendering in images",
      "ChatGPT integration",
      "Inpainting via editors",
      "Commercial use with Plus",
    ],
    ["Easy for beginners", "Strong prompt adherence", "Bundled with ChatGPT"],
    ["Less stylized than Midjourney", "Usage caps on free tier"],
    "Free credits / ChatGPT Plus",
    ["Midjourney", "Adobe Firefly", "Ideogram"],
  ),
  tool(
    27,
    "Stable Diffusion",
    "stability.ai",
    "AI Image",
    "Stable Diffusion is the best open-source AI image generator for local, customizable, and uncensored workflows. Free AI art model ecosystem with ControlNet, LoRAs, and ComfyUI—favorite of technical artists and indie hackers in 2026.",
    [
      "Open weights & local run",
      "LoRA & ControlNet ecosystem",
      "SDXL & SD3 models",
      "ComfyUI & Automatic1111",
      "API via Stability platform",
    ],
    ["Maximum control", "No vendor lock-in", "Huge community models"],
    ["Requires GPU for best speed", "Steep setup for beginners"],
    "Free (self-host) / Stability API",
    ["Midjourney", "Leonardo AI", "FLUX"],
  ),
  tool(
    28,
    "Adobe Firefly",
    "adobe.com",
    "AI Image",
    "Adobe Firefly is the best commercially safe AI image generator for Creative Cloud users. Trained on licensed content with Generative Fill in Photoshop—ideal for agencies needing IP-safe AI design assets in 2026.",
    [
      "Generative Fill in Photoshop",
      "Text to Image on web",
      "Content Credentials metadata",
      "Vector & template tools",
      "Enterprise indemnification",
    ],
    ["Commercially safe training", "Pro creative integrations", "Brand trust"],
    ["Requires Adobe subscription", "Less raw creativity than Midjourney"],
    "Free credits / Creative Cloud plans",
    ["DALL·E 3", "Canva AI", "Midjourney"],
  ),
  tool(
    29,
    "Leonardo AI",
    "leonardo.ai",
    "AI Image",
    "Leonardo AI is the best free AI image generator for game assets, character consistency, and fine-tuned models. AI art platform with Alchemy, Motion, and real-time canvas—perfect for indie game devs and illustrators on a budget.",
    [
      "Fine-tuned model library",
      "Character reference consistency",
      "Real-time generation canvas",
      "AI video & texture tools",
      "Daily free tokens",
    ],
    ["Generous free tokens", "Game-dev friendly", "Fast iteration UI"],
    ["Token system can confuse", "Busy interface"],
    "Free / Apprentice / Artisan / Maestro",
    ["Midjourney", "Playground AI", "Stable Diffusion"],
  ),
  tool(
    30,
    "Ideogram",
    "ideogram.ai",
    "AI Image",
    "Ideogram is the best AI image generator for typography, posters, and logos with accurate text. Free AI design tool specializing in readable words in images—essential for social media managers and print designers in 2026.",
    [
      "Best-in-class text rendering",
      "Poster & logo presets",
      "Remix & style controls",
      "Magic Prompt enhancement",
      "Community feeds",
    ],
    ["Superior text in images", "Great for marketing visuals", "Competitive free tier"],
    ["Less photoreal than Midjourney", "Queue times on free"],
    "Free / Basic / Plus / Pro",
    ["DALL·E 3", "Canva AI", "Adobe Firefly"],
  ),
  tool(
    31,
    "FLUX",
    "blackforestlabs.ai",
    "AI Image",
    "FLUX by Black Forest Labs is the best AI image model for photorealism and prompt fidelity in 2026. Top open and API-accessible generator rivaling Midjourney—available via Replicate, fal.ai, and partner apps for pro creators.",
    [
      "FLUX.1 Pro & Dev variants",
      "Exceptional human hands & skin",
      "API & self-host options",
      "Fast inference partners",
      "Strong typography vs SD",
    ],
    ["State-of-the-art realism", "Flexible deployment", "Creator-friendly licensing"],
    ["Pro API costs", "Less beginner UI than Canva"],
    "API pay-per-use / partner apps",
    ["Stable Diffusion", "Midjourney", "Leonardo AI"],
  ),
  tool(
    32,
    "Playground AI",
    "playground.com",
    "AI Image",
    "Playground AI is a top free AI image generator combining SDXL, DALL·E, and custom filters. Best AI art tool for social-ready graphics, product mockups, and collaborative boards with daily free generations.",
    [
      "Mixed models (SDXL, PG v2)",
      "Canvas editing & layers",
      "Community presets",
      "Background removal",
      "Commercial rights on Pro",
    ],
    ["Easy free daily credits", "Social template focus", "Collaborative boards"],
    ["Quality varies by model", "Pro needed for volume"],
    "Free / Pro / Turbo",
    ["Leonardo AI", "Ideogram", "Canva AI"],
  ),

  // AI Video (33-38)
  tool(
    33,
    "Runway",
    "runwayml.com",
    "AI Video",
    "Runway is the best AI video generator for Gen-3 cinematic clips, motion brush, and pro editing. Leading AI video tool for filmmakers and creators who need text-to-video, lip sync, and green screen AI effects in 2026.",
    [
      "Gen-3 Alpha text-to-video",
      "Motion Brush & Camera Control",
      "AI green screen & inpainting",
      "Image-to-video workflows",
      "Professional editor timeline",
    ],
    ["Hollywood-grade effects", "Cutting-edge models", "All-in-one suite"],
    ["Credit-based pricing", "Learning curve for pro tools"],
    "Free credits / Standard / Pro / Unlimited",
    ["Pika", "Luma Dream Machine", "Synthesia"],
  ),
  tool(
    34,
    "Synthesia",
    "synthesia.io",
    "AI Video",
    "Synthesia is the best AI video generator for corporate training and avatar presenters. Create AI talking-head videos in 140+ languages without cameras—top pick for L&D teams and enterprise comms in 2026.",
    [
      "140+ AI avatars",
      "Text-to-video in minutes",
      "Brand kit & templates",
      "SOC 2 & GDPR compliance",
      "Screen recording mix",
    ],
    ["Enterprise-ready", "No studio required", "Multilingual at scale"],
    ["Premium pricing", "Less creative than Runway"],
    "Starter $29/mo / Enterprise",
    ["HeyGen", "D-ID", "Colossyan"],
  ),
  tool(
    35,
    "Pictory",
    "pictory.ai",
    "AI Video",
    "Pictory is the best AI video tool for turning blog posts into YouTube and social clips. Automated text-to-video with stock footage, captions, and repurposing—ideal for content marketers scaling video SEO in 2026.",
    [
      "Article-to-video automation",
      "Auto captions & highlights",
      "Brand templates",
      "Teams & API",
      "Script to video",
    ],
    ["Fast repurposing", "Great for bloggers", "Caption accuracy"],
    ["Stock footage can feel generic", "Subscription for HD export"],
    "Starter $19/mo / Professional / Teams",
    ["Lumen5", "InVideo AI", "Opus Clip"],
  ),
  tool(
    36,
    "Lumen5",
    "lumen5.com",
    "AI Video",
    "Lumen5 is the best AI video maker for marketing teams turning articles into social video. Drag-and-drop AI video platform with media library and brand presets—perfect for B2B marketers needing consistent LinkedIn video content.",
    [
      "Blog-to-video wizard",
      "Stock media library",
      "Brand style lock",
      "Talking head templates",
      "Team workspaces",
    ],
    ["Marketing-friendly UX", "Reliable workflows", "Enterprise plans"],
    ["Less generative AI than Runway", "Template-heavy look"],
    "Free / Basic / Starter / Professional",
    ["Pictory", "InVideo AI", "Canva Video"],
  ),
  tool(
    37,
    "HeyGen",
    "heygen.com",
    "AI Video",
    "HeyGen is the best AI video generator for realistic avatars, lip sync, and UGC-style ads. Top AI spokesperson tool with Instant Avatar and Video Translate—must-have for ecommerce brands and course creators in 2026.",
    [
      "Instant & Studio Avatars",
      "Video Translate dubbing",
      "API for personalized video",
      "UGC ad templates",
      "Voice cloning integration",
    ],
    ["Highly realistic avatars", "Fast ad iteration", "Strong API story"],
    ["Credits burn quickly", "Ethical use policies"],
    "Free / Creator / Business / Enterprise",
    ["Synthesia", "D-ID", "Colossyan"],
  ),
  tool(
    38,
    "InVideo AI",
    "invideo.io",
    "AI Video",
    "InVideo AI is the best free AI video generator for prompt-based YouTube and ad videos. Text-to-video with script, voiceover, and stock clips—great for small businesses testing AI video marketing without editors.",
    [
      "Prompt-to-full video",
      "AI script writer",
      "5000+ templates",
      "Text-to-speech voices",
      "Direct social publishing",
    ],
    ["Beginner-friendly", "Large template library", "Affordable plans"],
    ["Less cinematic than Runway", "Watermark on free"],
    "Free / Plus / Max",
    ["Pictory", "Lumen5", "Canva Video"],
  ),

  // AI Audio (39-44)
  tool(
    39,
    "ElevenLabs",
    "elevenlabs.io",
    "AI Audio",
    "ElevenLabs is the best AI voice generator for realistic text-to-speech, cloning, and dubbing. Top AI audio tool for podcasts, audiobooks, and video narration with Voice Library and multilingual v2 models in 2026.",
    [
      "Ultra-realistic TTS",
      "Instant voice cloning",
      "Dubbing & translation",
      "Sound effects (FX)",
      "API & Projects studio",
    ],
    ["Best voice realism", "Creator-friendly UI", "Rapid model updates"],
    ["Paid for commercial scale", "Clone misuse policies"],
    "Free / Starter / Creator / Pro",
    ["Murf AI", "Play.ht", "Descript"],
  ),
  tool(
    40,
    "Murf AI",
    "murf.ai",
    "AI Audio",
    "Murf AI is the best AI voiceover tool for presentations, e-learning, and ads. Studio-quality AI audio generator with 120+ voices and pitch control—ideal for corporate training and explainer videos on a budget.",
    [
      "120+ voices & 20+ languages",
      "Pitch & pause control",
      "Google Slides add-on",
      "Team collaboration",
      "Canva & Adobe integrations",
    ],
    ["Great for slide narrations", "Clear commercial licensing", "Easy editor"],
    ["Less natural than ElevenLabs on clones", "Higher tiers for long form"],
    "Free trial / Basic / Pro / Enterprise",
    ["ElevenLabs", "Play.ht", "WellSaid"],
  ),
  tool(
    41,
    "Suno",
    "suno.com",
    "AI Audio",
    "Suno is the best AI music generator for full songs with vocals from text prompts. Viral free AI song maker for creators, memes, and prototyping—leading AI audio tool for royalty-aware music experiments in 2026.",
    [
      "Text-to-full song (v2)",
      "Custom lyrics mode",
      "Extend & cover features",
      "Mobile app",
      "Stem downloads (Pro)",
    ],
    ["Incredible musicality", "Fun & fast creation", "Strong community"],
    ["Copyright gray areas", "Commercial terms on paid"],
    "Free / Pro / Premier",
    ["Udio", "Soundraw", "AIVA"],
  ),
  tool(
    42,
    "Udio",
    "udio.com",
    "AI Audio",
    "Udio is the best AI music generator competing with Suno for studio-quality tracks. Create AI songs with genre control, inpainting, and stems—favorite of musicians exploring generative audio workflows in 2026.",
    [
      "High-fidelity music gen",
      "Inpaint sections",
      "Style & genre tags",
      "Extend track length",
      "Download WAV stems",
    ],
    ["Excellent production quality", "Musician-friendly controls", "Rapid iteration"],
    ["Waitlists & usage limits", "Licensing requires paid tier"],
    "Free / Standard / Pro",
    ["Suno", "Soundraw", "Beatoven.ai"],
  ),
  tool(
    43,
    "Descript",
    "descript.com",
    "AI Audio",
    "Descript is the best AI audio & video editor with text-based editing and Overdub voices. All-in-one podcast AI tool for transcription, filler removal, and screen recording—essential for creator teams in 2026.",
    [
      "Edit audio like a doc",
      "Overdub voice clone",
      "Studio Sound enhancement",
      "Filler word removal",
      "Video recording & captions",
    ],
    ["Revolutionary editing UX", "Strong podcast workflow", "Collaboration"],
    ["Learning curve", "Credits for AI features"],
    "Free / Hobbyist / Creator / Business",
    ["Adobe Podcast", "Riverside", "ElevenLabs"],
  ),
  tool(
    44,
    "Adobe Podcast",
    "adobe.com",
    "AI Audio",
    "Adobe Podcast (Enhance Speech) is the best free AI audio enhancer for cleaning voice recordings. One-click AI noise removal and studio sound for podcasters and YouTubers—powered by Adobe's speech AI research.",
    [
      "Enhance Speech v2",
      "Mic check AI analysis",
      "Browser-based workflow",
      "Project storage",
      "Integrates with Premiere",
    ],
    ["Free enhance tier", "Dramatic quality boost", "Trusted Adobe brand"],
    ["Not a full DAW", "Best as preprocessing step"],
    "Free / Express premium features",
    ["Descript", "Auphonic", "ElevenLabs"],
  ),

  // AI Design (45-50)
  tool(
    45,
    "Canva AI",
    "canva.com",
    "AI Design",
    "Canva AI is the best AI design tool for non-designers creating social posts, decks, and videos. Magic Studio bundles text-to-image, Magic Write, and background remover—top free AI graphic design platform in 2026.",
    [
      "Magic Media text-to-image",
      "Magic Write copy",
      "Brand Kit & templates",
      "AI video & present",
      "Teams & approval flows",
    ],
    ["Easiest for beginners", "Huge template market", "Affordable Pro plan"],
    ["Less precise than Figma", "AI credits on heavy use"],
    "Free / Pro $15/mo / Teams",
    ["Adobe Express", "Figma AI", "Visme"],
  ),
  tool(
    46,
    "Figma AI",
    "figma.com",
    "AI Design",
    "Figma AI brings generative design, rename layers, and prototype help inside the industry-standard UI tool. Best AI design assistant for product teams shipping design systems and dev handoff in 2026.",
    [
      "First Draft generative UI",
      "Rename layers & make designs",
      "FigJam AI brainstorming",
      "Dev Mode inspect",
      "Design systems & variables",
    ],
    ["Design team standard", "Collaborative realtime", "Strong AI roadmap"],
    ["AI features on paid plans", "Requires design skills"],
    "Free / Professional / Organization",
    ["Canva AI", "Framer", "Adobe XD"],
  ),
  tool(
    47,
    "Adobe Express",
    "adobe.com",
    "AI Design",
    "Adobe Express is the best free AI design app for quick social content with Firefly.generative tools. Mobile-friendly AI graphic designer with templates, video, and PDF tools—ideal for small business marketing.",
    [
      "Firefly generative fill",
      "Thousands of templates",
      "Quick actions & resize",
      "Video & animation",
      "Creative Cloud sync",
    ],
    ["Commercial-safe Firefly", "Free tier robust", "Adobe ecosystem"],
    ["Less powerful than Photoshop", "Template look risk"],
    "Free / Premium",
    ["Canva AI", "Visme", "Adobe Firefly"],
  ),
  tool(
    48,
    "Beautiful.ai",
    "beautiful.ai",
    "AI Design",
    "Beautiful.ai is the best AI presentation designer for smart slides that auto-layout. Free AI PowerPoint alternative with DesignerBot and team brand controls—perfect for sales decks and startup pitch presentations.",
    [
      "Smart slide templates",
      "DesignerBot AI decks",
      "Brand guardrails",
      "Analytics on views",
      "PowerPoint import/export",
    ],
    ["Slides always aligned", "Fast deck creation", "Sales-friendly"],
    ["Less flexible than Figma", "Subscription for exports"],
    "Free trial / Pro / Team",
    ["Gamma", "Canva Present", "Visme"],
  ),
  tool(
    49,
    "Visme",
    "visme.co",
    "AI Design",
    "Visme is the best AI design tool for infographics, reports, and interactive content. AI writer and chart tools for marketers who need data storytelling beyond basic Canva templates in 2026.",
    [
      "Infographic & report builder",
      "AI text & image tools",
      "Interactive embeds",
      "Analytics & lead gen",
      "Brand kit",
    ],
    ["Strong data viz", "B2B marketing focus", "Presentation + doc hybrid"],
    ["Steeper than Canva", "Premium for downloads"],
    "Free / Personal / Business",
    ["Canva AI", "Piktochart", "Beautiful.ai"],
  ),
  tool(
    50,
    "Framer AI",
    "framer.com",
    "AI Design",
    "Framer AI is the best AI website builder for designers publishing no-code sites with animations. Prompt-to-layout landing pages and CMS—top AI design tool for startups launching marketing sites fast in 2026.",
    [
      "AI page generation",
      "No-code responsive design",
      "Built-in CMS & SEO",
      "Animations & components",
      "Free hosting on framer.app",
    ],
    ["Designer-quality output", "Fast landing pages", "Great animations"],
    ["Not for complex web apps", "Custom code learning curve"],
    "Free / Mini / Basic / Pro",
    ["Webflow", "Wix ADI", "Figma AI"],
  ),

  // Productivity (51-56)
  tool(
    51,
    "Notion AI",
    "notion.so",
    "AI Productivity",
    "Notion AI is the best AI productivity tool inside your wiki, tasks, and docs. Summarize meetings, draft wikis, and autofill databases—essential AI workspace for remote teams and indie hackers organizing everything in one place.",
    [
      "Q&A over workspace",
      "Summarize & translate",
      "Autofill tables",
      "Action items from notes",
      "Templates marketplace",
    ],
    ["All-in-one workspace", "Flexible databases", "Strong team adoption"],
    ["AI add-on cost", "Can become complex"],
    "Free / Plus / Business + AI add-on",
    ["Mem", "Coda AI", "Obsidian"],
  ),
  tool(
    52,
    "Otter.ai",
    "otter.ai",
    "AI Productivity",
    "Otter.ai is the best AI meeting assistant for transcription, summaries, and action items. Free AI note-taker for Zoom, Google Meet, and Teams—must-have productivity AI tool for sales and product teams in 2026.",
    [
      "Live meeting transcription",
      "OtterPilot auto-join",
      "AI summary & outline",
      "Speaker identification",
      "Slack & CRM integrations",
    ],
    ["Accurate real-time notes", "Great free minutes", "Easy sharing"],
    ["Struggles with heavy accents", "Pro for long meetings"],
    "Free / Pro / Business",
    ["Fireflies.ai", "Fathom", "tl;dv"],
  ),
  tool(
    53,
    "Motion",
    "usemotion.com",
    "AI Productivity",
    "Motion is the best AI calendar and task planner that auto-schedules your day. Productivity AI tool that prioritizes work, blocks focus time, and manages projects—ideal for founders juggling too many deadlines.",
    [
      "AI auto-scheduling",
      "Task & project manager",
      "Meeting booking links",
      "Team capacity planning",
      "Focus time protection",
    ],
    ["Saves hours of planning", "Aggressive automation", "Great for executives"],
    ["Premium price", "Requires trust in AI scheduling"],
    "Individual $19/mo / Team",
    ["Reclaim.ai", "Sunsama", "Notion AI"],
  ),
  tool(
    54,
    "Reclaim.ai",
    "reclaim.ai",
    "AI Productivity",
    "Reclaim.ai is the best free AI scheduling assistant for Google Calendar habit stacking. Smart productivity tool for defending focus time, syncing tasks from Notion/Asana, and flexible meeting links.",
    [
      "Habits & smart meetings",
      "Task sync from PM tools",
      "Buffer & travel time",
      "Team scheduling analytics",
      "Free tier for individuals",
    ],
    ["Excellent Google Calendar fit", "Generous free plan", "Low setup"],
    ["Less project management than Motion", "Best inside Google stack"],
    "Free / Starter / Business / Enterprise",
    ["Motion", "Clockwise", "Calendly"],
  ),
  tool(
    55,
    "Zapier AI",
    "zapier.com",
    "AI Productivity",
    "Zapier AI is the best AI automation platform connecting 7000+ apps with natural language workflows. Build Zaps, Chatbots, and Agents—top productivity AI tool for no-code ops teams automating marketing and support in 2026.",
    [
      "AI-powered Zap builder",
      "Central AI chatbot",
      "Tables & Interfaces",
      "7000+ app integrations",
      "Human-in-the-loop approvals",
    ],
    ["Largest integration network", "Accessible no-code", "Enterprise scale"],
    ["Costs rise with tasks", "Complex Zaps need debugging"],
    "Free / Professional / Team / Enterprise",
    ["Make", "n8n", "Microsoft Power Automate"],
  ),
  tool(
    56,
    "Mem",
    "mem.ai",
    "AI Productivity",
    "Mem is the best AI notes app with self-organizing knowledge and Mem Chat. Personal productivity AI tool that captures ideas, resurfaces context, and drafts content—perfect for consultants and writers building a second brain.",
    [
      "Mem Chat over notes",
      "Auto-tagging & linking",
      "Voice & meeting capture",
      "Collections & templates",
      "iOS & web sync",
    ],
    ["Frictionless capture", "Smart resurfacing", "Modern UX"],
    ["Smaller ecosystem than Notion", "Subscription for full AI"],
    "Free / Mem X / Team",
    ["Notion AI", "Obsidian", "Roam Research"],
  ),
];

const rankings = [
  {
    id: 1,
    title: "Top 10 AI Coding Assistants in 2026",
    slug: "top-10-ai-coding-assistants-2026",
    description:
      "Compare the best AI coding assistants for VS Code, JetBrains, and cloud IDEs. From GitHub Copilot to Cursor and Codeium—find the top AI programmer tools for faster shipping in 2026.",
    tools: [17, 18, 19, 20, 21, 22, 23, 24],
    image: UNSPLASH.coding,
    seoTitle: "Top 10 AI Coding Assistants in 2026 | Best AI Programmer Tools",
    seoDescription:
      "Ranked list of the best AI coding assistants in 2026: Copilot, Cursor, Codeium, Tabnine, and more. Free & paid AI tools for developers and indie hackers.",
  },
  {
    id: 2,
    title: "Best Free AI Image Generators",
    slug: "best-free-ai-image-generators",
    description:
      "Discover the best free AI image generators for social posts, ads, and concept art. Leonardo AI, Ideogram, Playground, DALL·E, and Stable Diffusion compared for zero-budget creators.",
    tools: [26, 27, 29, 30, 32, 28],
    image: UNSPLASH.image,
    seoTitle: "Best Free AI Image Generators (2026) | Text-to-Image Tools",
    seoDescription:
      "Top free AI art and image generators in 2026. Compare DALL·E, Leonardo, Ideogram, Playground AI, and open-source Stable Diffusion for free AI images.",
  },
  {
    id: 3,
    title: "Must-have AI Tools for Indie Hackers",
    slug: "must-have-ai-tools-for-indie-hackers",
    description:
      "The ultimate stack of AI tools for solo founders: chatbots, coding IDEs, automation, and free AI writers. Ship your SaaS faster with ChatGPT, Cursor, Zapier AI, and Notion AI.",
    tools: [1, 5, 18, 10, 55, 51, 22, 29],
    image: UNSPLASH.indie,
    seoTitle: "Must-Have AI Tools for Indie Hackers (2026 Startup Stack)",
    seoDescription:
      "Best AI tools for indie hackers and solo founders: coding assistants, free AI writers, automation, and productivity apps to build and launch in 2026.",
  },
  {
    id: 4,
    title: "Top AI Video Generation Software",
    slug: "top-ai-video-generation-software",
    description:
      "Best AI video generation software for marketing, training, and YouTube. Runway Gen-3, HeyGen avatars, Synthesia, Pictory, and InVideo AI ranked for quality and ease of use.",
    tools: [33, 34, 35, 36, 37, 38],
    image: UNSPLASH.video,
    seoTitle: "Top AI Video Generation Software (2026) | Text-to-Video Tools",
    seoDescription:
      "Compare the best AI video generators in 2026: Runway, HeyGen, Synthesia, Pictory, Lumen5, and InVideo. Create AI videos without a studio.",
  },
  {
    id: 5,
    title: "Top 10 AI Writing Tools 2026",
    slug: "top-10-ai-writing-tools-2026",
    description:
      "Best AI writing tools for blogs, SEO, and marketing copy. Jasper, Copy.ai, Writesonic, Grammarly, and Rytr—ranked for quality, templates, and free AI writer tiers.",
    tools: [9, 10, 11, 12, 13, 16, 1],
    image: UNSPLASH.writing,
    seoTitle: "Top 10 AI Writing Tools for 2026 | Best Free AI Writers",
    seoDescription:
      "Discover the top AI writing tools in 2026 for SEO blogs, ads, and email. Compare Jasper, Copy.ai, Writesonic, Grammarly, and affordable free AI writers.",
  },
  {
    id: 6,
    title: "Top 10 AI Image Generators 2026",
    slug: "top-10-ai-image-generators-2026",
    description:
      "The most powerful AI image generators in 2026: Midjourney, FLUX, DALL·E 3, Adobe Firefly, and Leonardo. Best text-to-image AI tools for designers and marketers.",
    tools: [25, 26, 27, 28, 29, 30, 31, 32],
    image: UNSPLASH.image,
    seoTitle: "Top 10 AI Image Generators for 2026 | Best AI Art Tools",
    seoDescription:
      "Ranked top AI image generators in 2026: Midjourney, FLUX, DALL·E, Firefly, Leonardo, Ideogram. Create stunning AI art and marketing visuals.",
  },
  {
    id: 7,
    title: "Best AI Chatbots for Customer Support 2026",
    slug: "best-ai-chatbots-customer-support-2026",
    description:
      "Best AI chatbots for customer support, sales, and FAQ automation. ChatGPT, Claude, Gemini, Copilot, and Perplexity compared for accurate, grounded answers.",
    tools: [1, 2, 3, 4, 5, 8],
    image: UNSPLASH.support,
    seoTitle: "Best AI Chatbots for Customer Support (2026)",
    seoDescription:
      "Top AI chatbots for customer support and business in 2026. Compare ChatGPT, Claude, Gemini, Microsoft Copilot, and Perplexity for enterprise AI assistants.",
  },
  {
    id: 8,
    title: "Top AI Productivity Tools for Remote Teams",
    slug: "top-ai-productivity-tools-remote-teams",
    description:
      "Boost remote team productivity with Notion AI, Otter, Motion, Reclaim, Zapier AI, and Mem. Best AI workspace and meeting tools for distributed companies in 2026.",
    tools: [51, 52, 53, 54, 55, 56],
    image: UNSPLASH.productivity,
    seoTitle: "Top AI Productivity Tools for Remote Teams (2026)",
    seoDescription:
      "Best AI productivity tools for remote teams: Notion AI, Otter.ai, Motion, Reclaim, Zapier, and Mem. Automate notes, scheduling, and workflows in 2026.",
  },
  {
    id: 9,
    title: "Best AI Voice & Audio Tools 2026",
    slug: "best-ai-voice-audio-tools-2026",
    description:
      "Top AI voice generators and audio editors: ElevenLabs, Murf, Suno, Udio, Descript, and Adobe Podcast. Best AI audio tools for podcasts, music, and video dubbing.",
    tools: [39, 40, 41, 42, 43, 44],
    image: UNSPLASH.audio,
    seoTitle: "Best AI Voice & Audio Tools (2026) | TTS & Music AI",
    seoDescription:
      "Compare the best AI voice generators and AI music tools in 2026: ElevenLabs, Murf, Suno, Udio, Descript. Free and paid AI audio for creators.",
  },
  {
    id: 10,
    title: "Top AI Design Tools for Marketers",
    slug: "top-ai-design-tools-for-marketers",
    description:
      "Best AI design tools for marketing teams: Canva AI, Adobe Express, Visme, Beautiful.ai, and Figma AI. Create ads, decks, and infographics with generative AI in minutes.",
    tools: [45, 47, 49, 48, 46, 30],
    image: UNSPLASH.design,
    seoTitle: "Top AI Design Tools for Marketers (2026)",
    seoDescription:
      "Best AI graphic design tools for marketers in 2026: Canva, Adobe Express, Visme, Beautiful.ai, Figma AI. Free AI design for social and ads.",
  },
  {
    id: 11,
    title: "Best AI Tools for Content Creators",
    slug: "best-ai-tools-for-content-creators",
    description:
      "Creator stack: ChatGPT, Midjourney, Runway, ElevenLabs, Pictory, and Canva AI. The best AI tools for YouTubers, TikTokers, and newsletter writers scaling content in 2026.",
    tools: [1, 25, 33, 39, 35, 45, 41],
    image: UNSPLASH.creator,
    seoTitle: "Best AI Tools for Content Creators (2026)",
    seoDescription:
      "Top AI tools for content creators: writing, image, video, voice, and design AI apps for YouTube, TikTok, and social media growth in 2026.",
  },
  {
    id: 12,
    title: "Top Free AI Tools in 2026",
    slug: "top-free-ai-tools-2026",
    description:
      "The best free AI tools you can use today: ChatGPT, Gemini, Perplexity, Codeium, Leonardo, Copy.ai, Otter, and Canva. No credit card required to start.",
    tools: [1, 3, 5, 22, 29, 10, 52, 45],
    image: UNSPLASH.free,
    seoTitle: "Top Free AI Tools in 2026 (No Credit Card)",
    seoDescription:
      "Best free AI tools in 2026: free AI chatbots, coders, image generators, writers, and meeting assistants. Start with zero budget.",
  },
  {
    id: 13,
    title: "Best AI Presentation & Slide Tools",
    slug: "best-ai-presentation-slide-tools",
    description:
      "Best AI presentation makers: Beautiful.ai, Canva Present, Visme, and Figma slides. Generate pitch decks and sales slides with AI layout and copy in 2026.",
    tools: [48, 45, 49, 46],
    image: UNSPLASH.presentation,
    seoTitle: "Best AI Presentation Tools (2026) | AI Slide Deck Makers",
    seoDescription:
      "Top AI presentation and slide tools in 2026. Beautiful.ai, Canva, Visme, and Figma AI for automated pitch decks and marketing slides.",
  },
  {
    id: 14,
    title: "Top AI Music Generators: Suno vs Udio",
    slug: "top-ai-music-generators-suno-vs-udio",
    description:
      "Compare the best AI music generators Suno and Udio for full songs with vocals. Plus alternatives for royalty-free background tracks and creator workflows in 2026.",
    tools: [41, 42, 39],
    image: UNSPLASH.music,
    seoTitle: "Top AI Music Generators 2026 | Suno vs Udio Compared",
    seoDescription:
      "Best AI music generators in 2026: Suno vs Udio for AI songs with vocals. Free AI music tools for creators, video, and podcasts.",
  },
  {
    id: 15,
    title: "Best AI Meeting & Note-Taking Tools",
    slug: "best-ai-meeting-note-taking-tools",
    description:
      "Best AI meeting assistants: Otter.ai, Notion AI, Descript, and Mem. Transcribe Zoom calls, summarize action items, and sync notes to your wiki automatically.",
    tools: [52, 51, 43, 56],
    image: UNSPLASH.meeting,
    seoTitle: "Best AI Meeting & Note-Taking Tools (2026)",
    seoDescription:
      "Top AI meeting transcription and note-taking tools in 2026: Otter, Notion AI, Descript, Mem. Free AI meeting summaries for remote teams.",
  },
  {
    id: 16,
    title: "Top AI Tools for Startups & SaaS",
    slug: "top-ai-tools-for-startups-saas",
    description:
      "AI stack for startups: Claude for docs, Cursor for code, Jasper for GTM copy, Zapier for ops, and Perplexity for research. Scale your SaaS with the best AI tools in 2026.",
    tools: [2, 18, 9, 55, 5, 34],
    image: UNSPLASH.startup,
    seoTitle: "Top AI Tools for Startups & SaaS (2026)",
    seoDescription:
      "Best AI tools for startups and SaaS teams in 2026: coding, writing, automation, research, and video AI for lean growth teams.",
  },
  {
    id: 17,
    title: "Best AI SEO & Marketing Writing Tools",
    slug: "best-ai-seo-marketing-writing-tools",
    description:
      "Best AI writers for SEO blogs, ad copy, and conversion: Jasper, Writesonic, Anyword, Copy.ai, and Grammarly. Rank higher with AI content workflows in 2026.",
    tools: [9, 11, 16, 10, 12],
    image: UNSPLASH.marketing,
    seoTitle: "Best AI SEO & Marketing Writing Tools (2026)",
    seoDescription:
      "Top AI SEO writing tools and marketing copy generators in 2026. Jasper, Writesonic, Anyword, Copy.ai for blogs, ads, and landing pages.",
  },
  {
    id: 18,
    title: "Top AI Video Editors for YouTube Creators",
    slug: "top-ai-video-editors-youtube-creators",
    description:
      "Best AI video tools for YouTube: Pictory, InVideo AI, Descript, Runway, and Lumen5. Repurpose blogs into clips, auto-captions, and generative B-roll for creators.",
    tools: [35, 38, 43, 33, 36],
    image: UNSPLASH.youtube,
    seoTitle: "Top AI Video Editors for YouTube Creators (2026)",
    seoDescription:
      "Best AI video editing and repurposing tools for YouTube in 2026: Pictory, InVideo, Descript, Runway, Lumen5. Grow your channel with AI.",
  },
  {
    id: 19,
    title: "Best Claude & GPT Alternatives 2026",
    slug: "best-claude-gpt-alternatives-2026",
    description:
      "Top alternatives to ChatGPT and Claude: Google Gemini, Perplexity, Poe, Meta AI, and Microsoft Copilot. Compare free AI chatbots for research, coding, and writing.",
    tools: [3, 4, 5, 6, 8, 2],
    image: UNSPLASH.alternatives,
    seoTitle: "Best Claude & ChatGPT Alternatives (2026)",
    seoDescription:
      "Best ChatGPT and Claude alternatives in 2026: Gemini, Copilot, Perplexity, Poe, Meta AI. Free AI chatbots compared.",
  },
  {
    id: 20,
    title: "Top AI Automation Tools for No-Code Teams",
    slug: "top-ai-automation-tools-no-code-teams",
    description:
      "Best AI automation platforms: Zapier AI, Notion AI, and Copilot in Microsoft 365. Build workflows, chatbots, and agents without engineering headcount in 2026.",
    tools: [55, 51, 4, 10],
    image: UNSPLASH.automation,
    seoTitle: "Top AI Automation Tools for No-Code Teams (2026)",
    seoDescription:
      "Best AI automation tools in 2026 for no-code teams: Zapier AI, Notion AI, Microsoft Copilot. Automate marketing, sales, and ops workflows.",
  },
];

const categories = [
  {
    slug: "ai-chatbots",
    name: "AI Chatbots",
    description:
      "Best AI chatbots and conversational assistants for support, research, coding, and daily productivity.",
    icon: "💬",
  },
  {
    slug: "ai-writing",
    name: "AI Writing",
    description:
      "AI writing tools, free AI writers, copy generators, and SEO content assistants for blogs and marketing.",
    icon: "✍️",
  },
  {
    slug: "ai-coding",
    name: "AI Coding",
    description:
      "AI coding assistants, IDE copilots, and agentic programming tools for developers and indie hackers.",
    icon: "💻",
  },
  {
    slug: "ai-image",
    name: "AI Image",
    description:
      "AI image generators, text-to-image models, and free AI art tools for design and social media.",
    icon: "🖼️",
  },
  {
    slug: "ai-video",
    name: "AI Video",
    description:
      "AI video generators, text-to-video software, and AI editing tools for YouTube and marketing.",
    icon: "🎬",
  },
  {
    slug: "ai-audio",
    name: "AI Audio",
    description:
      "AI voice generators, text-to-speech, AI music makers, and podcast audio enhancement tools.",
    icon: "🎵",
  },
  {
    slug: "ai-design",
    name: "AI Design",
    description:
      "AI design tools for graphics, presentations, websites, and brand assets without a design degree.",
    icon: "🎨",
  },
  {
    slug: "productivity",
    name: "Productivity",
    description:
      "AI productivity tools for notes, meetings, scheduling, automation, and team knowledge management.",
    icon: "⚡",
  },
];

const root = join(process.cwd(), "data");
writeFileSync(join(root, "tools.json"), JSON.stringify(tools, null, 2) + "\n");
writeFileSync(join(root, "rankings.json"), JSON.stringify(rankings, null, 2) + "\n");
writeFileSync(join(root, "categories.json"), JSON.stringify(categories, null, 2) + "\n");

console.log(`Generated ${tools.length} tools, ${rankings.length} rankings, ${categories.length} categories`);
